### ISSUE TITLE
Example usage section

### ISSUE THREAD

**Issue by druvus** [naturalis/wgs2ncbi#13]
I think it would be preferable to add an Example usage section to README. It was not obvious which ini-file that should be used.  

Just mention in the added section that `wgs2ncbi.ini` in the share folder could be used to check the functionallity of wgs2ncbi and add all commands in a code block. 

```
wgs2ncbi prepare -conf  wgs2ncbi.ini
wgs2ncbi process -conf wgs2ncbi.ini
wg2ncbi convert -conf wgs2ncbi.ini
wgs2ncbi compress -conf wgs2ncbi.ini
```

**Comment by rvosa** [comment]
I have extensively rewritten the README (which admittedly needed some work). I think this addresses your remarks sufficiently, as all the involved files are explained.
