### ISSUE TITLE
Minor usage comments

### ISSUE THREAD

**Issue by druvus** [naturalis/wgs2ncbi#14]
I think the usage experience of wgs2ncbi could be improved by adding some information what is created in each subcommand. Right now it is hard to know if the command were successful and what it created. It could be done as updating documentation to describe output for each step or that wgs2ncbi writes out that information to the screen for each command. 

It would also be nice to have som indication if the command run successfully or not. For instance it doesn't give any information or error if tbl2asn is not installed.

**Comment by rvosa** [comment]
I now describe for each step what the expected output is. No expected output = no success. I assume that this issue is hereby sufficiently addressed.
