### ISSUE TITLE
Bioconda package

### ISSUE THREAD

**Issue by druvus** [naturalis/wgs2ncbi#15]
I started to package wgs2ncbi as Bioconda package (see bioconda/bioconda-recipes#14434) as I think it will help spreading the software to more users. I will keep it on hold until the last minor fixes are included in a new tagged release.

**Comment by rvosa** [comment]
That's great, thanks! If it's alright with you I will go ahead and address the other issues you've posted and close this one as it's not really an action item for me to deal with.
